name: Main CI/CD

on:
  push:
    branches:
      - dev
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  security-events: write  
jobs:
  get-json-values:
    runs-on: ubuntu-latest
    outputs:
      build_code: ${{ steps.config.outputs.build_code }}
      build_docker: ${{ steps.config.outputs.build_docker }}
      codeql: ${{ steps.config.outputs.codeql }}
      deploy: ${{ steps.config.outputs.deploy }}
      image_tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      # Read config.json
      - name: Read config.json
        id: config
        run: |
          echo "build_code=$(jq -r '.build_code' config.json)" >> $GITHUB_OUTPUT
          echo "build_docker=$(jq -r '.build_docker' config.json)" >> $GITHUB_OUTPUT
          echo "codeql=$(jq -r '.codeql' config.json)" >> $GITHUB_OUTPUT
          echo "deploy=$(jq -r '.deploy // "false"' config.json)" >> $GITHUB_OUTPUT

      # Generate an image tag (based on short commit SHA)
      - name: Generate image tag
        id: meta
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  run-ci-cd:
    needs: get-json-values
    uses: Saimsc/cd-template/.github/workflows/cd-main.yml@dev
    with:
      build_code: ${{ needs.get-json-values.outputs.build_code }}
      build_docker: ${{ needs.get-json-values.outputs.build_docker }}
      codeql: ${{ needs.get-json-values.outputs.codeql }}
      deploy: ${{ needs.get-json-values.outputs.deploy }}
      image_tag: ${{ needs.get-json-values.outputs.image_tag }}
